# file: .github/workflows/hello-world.yml
name: my test
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # print – произвольно выбранное имя задания
  # их может быть больше одного
  all-tasks:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: wearerequired/lint-action@v2
      # Ставим зависимости
      - run: make setup
      #- run: npm install
    #  - run: npm run build
      - run: make start 
      # Запускаем линтер
      - run: make lint
      #- run: npm run lint
      - run: make test
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      #- run: make setup
      #- run: make test
     # - run: make lint
